# Generated by Django 3.0.8 on 2020-08-19 03:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('CreateDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('Name', models.CharField(max_length=128, verbose_name='Name')),
                ('FilePath', models.CharField(max_length=128, verbose_name='Path')),
            ],
            options={
                'verbose_name': 'File Path',
                'verbose_name_plural': 'File Path',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('CreateDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('Name', models.CharField(max_length=128, verbose_name='Name')),
                ('Path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.Path')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Package',
            },
        ),
    ]
